---
# Tasks for the base CDF installation

- name: Install Java JDK 1.8
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
  tags: [setup]

- name: create nifi system group
  group:
    name: "{{ nifi_run_as }}"
    state: present
  when: nifi_run_as != "root"
  tags: [setup]

- name: create nifi system account
  user:
    name: "{{ nifi_run_as }}"
    groups: cdf,cfm
    append: yes
    system: yes
    state: present
  when: nifi_run_as != "root"
  tags: [setup]

- name: Create CFM NiFi Directory
  file:
    path: /usr/cdf/cfm/nifi/
    owner: nifi
    group: cfm
    state: directory
    mode: 0775
  tags: [setup]

- name: set nofile ulimit to {{ pam_limits_nofile }}
  pam_limits:
    domain: '*'
    limit_type: "{{ item }}"
    limit_item: nofile
    value: "{{ pam_limits_nofile }}"
    use_max: yes
    backup: yes
  with_items:
    - hard
    - soft
  tags: [setup]

- name: set nproc ulimit to {{ pam_limits_nproc }}
  pam_limits:
    domain: '*'
    limit_type: "{{ item }}"
    limit_item: nproc
    value: "{{ pam_limits_nproc }}"
    use_max: yes
    backup: yes
  with_items:
    - hard
    - soft
  tags: [setup]

- name: set net.ipv4.ip_local_port_range={{ net_ipv4_ip_local_port_range }}
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "{{ net_ipv4_ip_local_port_range }}"
    sysctl_set: yes
    state: present
    reload: yes
  tags: [setup]

- name: set vm.swapiness={{ vm_swapiness }}
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^vm.swapiness='
    line: vm.swapiness={{ vm_swapiness }}
    backup: yes
  tags: [setup]